---
all:
  children:
    cisco_ios:
      hosts:
        rtr01:
          ansible_host: 192.0.2.11
          device_role: router
        sw01:
          ansible_host: 192.0.2.21
          device_role: access_switch
        sw02:
          ansible_host: 192.0.2.22
          device_role: access_switch
