---
- name: Definizione dello stato dichiarativo delle VLAN
  hosts: cisco_switches
  gather_facts: false

  tasks:
    - name: Assicura la presenza delle VLAN aziendali
      cisco.ios.ios_vlans:
        state: merged
        config:
          - vlan_id: 10
            name: MANAGEMENT
          - vlan_id: 20
            name: DATA_LAN
          - vlan_id: 30
            name: VOIP
          - vlan_id: 99
            name: NATIVE_GUEST
