[cisco_switches]
switch01 ansible_host=192.168.1.11
switch02 ansible_host=192.168.1.12

[cisco_routers]
router01 ansible_host=192.168.1.1
router02 ansible_host=192.168.1.2

[cisco_all:children]
cisco_switches
cisco_routers

[cisco_all:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_user=netadmin
# ansible_ssh_pass da gestire con Ansible Vault, NON in chiaro
